version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    container_name: payhere
    ports:
      - "4000:3306"
    environment:
      - MYSQL_PASSWORD=payhere
      - MYSQL_USER=payhere
      - MYSQL_DATABASE=payhere
      - MYSQL_ROOT_PASSWORD=payhere
      - MYSQL_ROOT_HOST=%
    command:
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-server=utf8mb4
    networks:
      - payhere_network

  application:
    container_name: payhere_spring
    restart: on-failure
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:4000/payhere
      SPRING_DATASOURCE_USERNAME: "payhere"
      SPRING_DATASOURCE_PASSWORD: "payhere"
    links:
      - db
    depends_on :
      - db
    networks:
      - payhere_network
networks:
   payhere_network :
